//
//  MovieDetailRouter.swift
//  BAZProject
//
//  Created Cristian Eduardo Villegas Alvarez on 17/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Cristian Villegas
//

import UIKit

class MovieDetailRouter: MovieDetailWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(previusImage:UIImage? = nil,movie:CVMovieHubViewEntityMovieItem) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MovieDetailViewController(nibName: "MovieDetailViewController", bundle: Bundle(for: MovieDetailViewController.self))
        view.movieItem = movie
        view.previusImage = previusImage
        let interactor = MovieDetailInteractor()
        let router = MovieDetailRouter()
        let presenter = MovieDetailPresenter(interface: view, interactor: interactor, router: router)
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        return view
    }
}
