//
//  MovieDetailViewController.swift
//  BAZProject
//
//  Created Cristian Eduardo Villegas Alvarez on 17/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Cristian Villegas
//

import UIKit

class MovieDetailViewController: UIViewController, MovieDetailViewProtocol {

    @IBOutlet weak var opacityLayer:UIView!
    @IBOutlet weak var contentView:UIView!
    var previusImage:UIImage? = nil
    @IBOutlet weak var cartelImage:UIImageView!
    @IBOutlet weak var titleLabel:UILabel!
    @IBOutlet weak var closeButton:UIButton!
    @IBOutlet weak var sinopsisLabel:UILabel!
	var presenter: MovieDetailPresenterProtocol?
    
    var movieItem:CVMovieHubViewEntityMovieItem? = nil

	override func viewDidLoad() {
        super.viewDidLoad()
        self.opacityLayer.layer.opacity = 0
        self.cartelImage.layer.opacity = 0
        self.closeButton.layer.opacity = 0
        self.sinopsisLabel.layer.opacity = 0
        self.titleLabel.layer.opacity = 0
        self.cartelImage.layer.cornerRadius = 16
        self.cartelImage.layer.masksToBounds = true
        if let image = self.previusImage {
            self.cartelImage.image = image
        }
        titleLabel.text = movieItem?.title ?? ""
        sinopsisLabel.text = movieItem?.description
    }
    
    override func viewDidAppear(_ animated: Bool) {
        self.view.bringSubviewToFront(self.opacityLayer)
        self.view.bringSubviewToFront(self.contentView)
       
        UIView.animate(withDuration: 0.3, animations: {
            self.opacityLayer.layer.opacity = 1
            self.cartelImage.layer.opacity = 1
            self.closeButton.layer.opacity = 1
            self.sinopsisLabel.layer.opacity = 1
            self.titleLabel.layer.opacity = 1
        })
        self.removeAllKeyboards()
    }
    
    @IBAction func tryClose(){
        self.dismiss(animated: true)
    }

}
