//
//  MovieDetailPresenter.swift
//  BAZProject
//
//  Created Cristian Eduardo Villegas Alvarez on 17/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Cristian Villegas
//

import UIKit

class MovieDetailPresenter: MovieDetailPresenterProtocol {

    weak private var view: MovieDetailViewProtocol?
    var interactor: MovieDetailInteractorProtocol?
    private let router: MovieDetailWireframeProtocol

    init(interface: MovieDetailViewProtocol, interactor: MovieDetailInteractorProtocol?, router: MovieDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
