//
//  MovieDetailInteractor.swift
//  BAZProject
//
//  Created Cristian Eduardo Villegas Alvarez on 17/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Cristian Villegas
//

import UIKit

class MovieDetailInteractor: MovieDetailInteractorProtocol {

    weak var presenter: MovieDetailPresenterProtocol?
}
