//
//  MovieDetailProtocols.swift
//  BAZProject
//
//  Created Cristian Eduardo Villegas Alvarez on 17/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Cristian Villegas
//

import Foundation

//MARK: Wireframe -
protocol MovieDetailWireframeProtocol: class {

}
//MARK: Presenter -
protocol MovieDetailPresenterProtocol: class {

}

//MARK: Interactor -
protocol MovieDetailInteractorProtocol: class {

  var presenter: MovieDetailPresenterProtocol?  { get set }
}

//MARK: View -
protocol MovieDetailViewProtocol: class {

  var presenter: MovieDetailPresenterProtocol?  { get set }
}
