//
//  MovieHubRouter.swift
//  BAZProject
//
//  Created Cristian Eduardo Villegas Alvarez on 11/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Cristian Villegas
//

import UIKit

class MovieHubRouter: MovieHubWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MovieHubViewController(nibName: "MovieHubViewController", bundle: Bundle(for: MovieHubViewController.self))
        let interactor = MovieHubInteractor()
        let router = MovieHubRouter()
        let presenter = MovieHubPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
