//
//  MovieHubProtocols.swift
//  BAZProject
//
//  Created Cristian Eduardo Villegas Alvarez on 11/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Cristian Villegas
//

import Foundation

//MARK: Wireframe -
protocol MovieHubWireframeProtocol: AnyObject {
    
}
//MARK: Presenter -
protocol MovieHubPresenterProtocol: AnyObject {
    func tryFetchSections()
    func onSectionsFetch(sections:[CVMovieHubViewEntitySection])
    var configuration:[CVMovieHubViewEntitySection] {get set}
    func filterConfigurationByTitle(_ title: String)
    func unfilterConfiguration()
    var filteredConfiguration:[CVMovieHubViewEntitySection] {get set}
}

//MARK: Interactor -
protocol MovieHubInteractorProtocol: AnyObject {
    func tryFetchSections()
    func onSectionsFetch(sections:[CVMovieHubViewEntitySection])
    var presenter: MovieHubPresenterProtocol?  { get set }
    
}

//MARK: View -
protocol MovieHubViewProtocol: AnyObject {
    func onSectionsFetch(sections:[CVMovieHubViewEntitySection])
    var presenter: MovieHubPresenterProtocol?  { get set }
}
