//
//  MovieHubPresenter.swift
//  BAZProject
//
//  Created Cristian Eduardo Villegas Alvarez on 11/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Cristian Villegas
//

import UIKit

class MovieHubPresenter: MovieHubPresenterProtocol {
    
    
    var configuration:[CVMovieHubViewEntitySection] = []
    
    func onSectionsFetch(sections: [CVMovieHubViewEntitySection]) {
        self.configuration = sections
        self.view?.onSectionsFetch(sections: sections)
    }
    

    weak private var view: MovieHubViewProtocol?
    var interactor: MovieHubInteractorProtocol?
    private let router: MovieHubWireframeProtocol

    func tryFetchSections() {
        interactor?.tryFetchSections()
    }
    init(interface: MovieHubViewProtocol, interactor: MovieHubInteractorProtocol?, router: MovieHubWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
