//
//  MovieHubInteractor.swift
//  BAZProject
//
//  Created Cristian Eduardo Villegas Alvarez on 11/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Cristian Villegas
//

import UIKit

class MovieHubInteractor: MovieHubInteractorProtocol {
    
    func onSectionsFetch(sections: [CVMovieHubViewEntitySection]) {
        presenter?.onSectionsFetch(sections: sections)
    }
    
    
    
    func tryFetchSections() {
        CVMovieApiManager().getMovies { sections in
            self.presenter?.onSectionsFetch(sections: sections.configuration)
        }
    }
    
 
    

    weak var presenter: MovieHubPresenterProtocol?
}
