//
//  HomeMovieAppRouter.swift
//  BAZProject
//
//  Created Brenda Paola Lara Moreno on 24/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Pedro Vazquez @pedrovazquezax2
//

import UIKit

class HomeMovieAppRouter: HomeMovieAppRouterProtocol {
    var navigation: UINavigationController?
//    static var mainStoryboard: UIStoryboard {
//    return UIStoryboard(name: "HomeMovieAppStoryboard", bundle: Bundle.main)
//    }

    static func createModule(navigation:UINavigationController) -> UIViewController {

        let view = HomeMovieAppViewController()
        let presenter = HomeMovieAppPresenter()
        let interactor = HomeMovieAppInteractor()
        let router = HomeMovieAppRouter()
        
        view.presenter = presenter
        presenter.interactor = interactor
        presenter.router = router
        presenter.view = view
        interactor.presenter = presenter
        router.navigation = navigation
        
        return view
    }
    
    func nextViewNavigation() {

    }
}
