//
//  MovieAppRouter.swift
//  BAZProject
//
//  Created Brenda Paola Lara Moreno on 09/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Pedro Vazquez @pedrovazquezax2
//

import UIKit

class MovieAppRouter: MovieAppRouterProtocol {
    var navigation: UINavigationController?
//    static var mainStoryboard: UIStoryboard {
//    return UIStoryboard(name: "MovieAppStoryboard", bundle: Bundle.main)
//    }

    static func createModule(navigation:UINavigationController) -> UIViewController {

        let view = MovieAppViewController()
        let presenter = MovieAppPresenter()
        let interactor = MovieAppInteractor()
        let router = MovieAppRouter()
        
        view.presenter = presenter
        presenter.interactor = interactor
        presenter.router = router
        presenter.view = view
        interactor.presenter = presenter
        router.navigation = navigation
        
        return view
    }
    
    func nextViewNavigation() {

    }
}
