//
//  HomeMovieAppProtocols.swift
//  BAZProject
//
//  Created Brenda Paola Lara Moreno on 24/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Pedro Vazquez @pedrovazquezax2
//

import Foundation
protocol HomeMovieAppViewProtocol: class {
    var presenter: HomeMovieAppPresenterProtocol? { get }
    
}
protocol HomeMovieAppPresenterProtocol: class {
    var view: HomeMovieAppViewProtocol? { get }
    var interactor: HomeMovieAppInteractorProtocol? { get }
    var router: HomeMovieAppRouterProtocol?  { get }
}

protocol HomeMovieAppInteractorProtocol: class  {
    var presenter: HomeMovieAppInteractorOutputProtocol? { get }
}
protocol HomeMovieAppInteractorOutputProtocol: class {
    
}

protocol HomeMovieAppRouterProtocol: class {
    func nextViewNavigation()
}