//
//  MovieAppProtocols.swift
//  BAZProject
//
//  Created Brenda Paola Lara Moreno on 09/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Pedro Vazquez @pedrovazquezax2
//

import Foundation
protocol MovieAppViewProtocol: AnyObject{
    var presenter: MovieAppPresenterProtocol? { get }
    
}
protocol MovieAppPresenterProtocol: AnyObject {
    var view: MovieAppViewProtocol? { get }
    var interactor: MovieAppInteractorProtocol? { get }
    var router: MovieAppRouterProtocol?  { get }
}

protocol MovieAppInteractorProtocol: AnyObject  {
    var presenter: MovieAppInteractorOutputProtocol? { get }
}
protocol MovieAppInteractorOutputProtocol: AnyObject {
    
}

protocol MovieAppRouterProtocol: AnyObject {
    func nextViewNavigation()
}
