//
//  MovieAppInteractor.swift
//  BAZProject
//
//  Created Brenda Paola Lara Moreno on 09/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Pedro Vazquez @pedrovazquezax2
//
import Foundation

class MovieAppInteractor: MovieAppInteractorProtocol {
    weak var presenter: MovieAppInteractorOutputProtocol?
}