//
//  MovieAppViewController.swift
//  BAZProject
//
//  Created Brenda Paola Lara Moreno on 09/02/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Pedro Vazquez @pedrovazquezax2
//

import UIKit

class MovieAppViewController: UIViewController {
    var presenter: MovieAppPresenterProtocol?

    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
    }


    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destination.
        // Pass the selected object to the new view controller.
    }
    */

}
extension MovieAppViewController: MovieAppViewProtocol {
    
    
}
